Revert "00boot: run autoreconf verbosely" This reverts commit 6d316ad61372b5ac4297f383e6b7ff11d9a69111. Original: 22056a9b626c5568bdae68cfe2db8f247867f3d7

diff --git a/lalapps/00boot b/lalapps/00boot
--- a/lalapps/00boot
+++ b/lalapps/00boot
@@ -25,7 +25,7 @@ rm -f aclocal.m4
 ## run autoreconf
 AUTORECONF=${AUTORECONF:-"autoreconf"}
 echo "00boot: running ${AUTORECONF}"
-LIBTOOLIZE=true ${AUTORECONF} --verbose || fail "${AUTORECONF} failed"
+LIBTOOLIZE=true ${AUTORECONF} || fail "${AUTORECONF} failed"
 
 echo "
 ==================================================
