added info to 00boot Original: de37cc11c36aac96125b323cdb4ab9f5351da1ee

diff --git a/lalapps/00boot b/lalapps/00boot
--- a/lalapps/00boot
+++ b/lalapps/00boot
@@ -2,6 +2,13 @@
 #
 # $Id$
 
+## Function to report failure
+fail () {
+  echo "!!! 00boot: $1 failed" >&2
+  echo "!!! 00boot: consult the file 'README' for help" >&2
+  exit 1
+}
+
 # Help message
 helpmsg="Usage $0 [options]
 Options: [defaults in brackets after description]"
@@ -39,18 +46,58 @@ while test $# -gt 0 ; do
   shift
 done
 
-AUTOMAKE="${AUTOMAKE:-automake}"
-ACLOCAL="${ACLOCAL:-aclocal}"
-AUTOCONF="${AUTOCONF:-autoconf}"
-AUTOHEADER="${AUTOHEADER:-autoheader}"
+echo ">>> 00boot: checking versions of aclocal, automake, autoheader and autoconf"
 
-echo "Using:
-aclocal:        `which $ACLOCAL`
-automake:       `which $AUTOMAKE`
-autoheader:     `which $AUTOHEADER`
-autoconf:       `which $AUTOCONF`"
 
-$ACLOCAL
-$AUTOHEADER
-$AUTOMAKE $INCLUDEDEPS
-$AUTOCONF
+ACLOCAL=${ACLOCAL:-"aclocal"}
+AUTOMAKE=${AUTOMAKE:-"automake"}
+AUTOCONF=${AUTOCONF:-"autoconf"}
+AUTOHEADER=${AUTOHEADER:-"autoheader"}
+
+automake_version="`$AUTOMAKE --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
+aclocal_version="`$ACLOCAL --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
+autoheader_version="`$AUTOHEADER --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
+autoconf_version="`$AUTOCONF --version 2>/dev/null | sed -n '1s/^.* \([0-9.]*\)/\1/p'`"
+if test -z "$aclocal_version"; then
+  fail "finding program aclocal"
+fi
+if test -z "$automake_version"; then
+  fail "finding program automake"
+fi
+if test -z "$autoconf_version"; then
+  fail "finding program autoconf"
+fi
+if test -z "$autoheader_version"; then
+  fail "finding program autoheader"
+fi
+
+echo ">>> 00boot: using:"
+printf ">>> 00boot:\t%-16s %s\n" "aclocal-$aclocal_version:" "`which $ACLOCAL`"
+printf ">>> 00boot:\t%-16s %s\n" "automake-$automake_version:" "`which $AUTOMAKE`"
+printf ">>> 00boot:\t%-16s %s\n" "autoheader-$autoheader_version:" "`which $AUTOHEADER`"
+printf ">>> 00boot:\t%-16s %s\n" "autoconf-$autoconf_version:" "`which $AUTOCONF`"
+
+## Generate the Makefile.in's and the configure script
+
+echo ">>> 00boot: running aclocal"
+$ACLOCAL || fail "aclocal"
+echo ">>> 00boot: running autoheader"
+$AUTOHEADER || fail "autoheader"
+echo ">>> 00boot: running automake"
+$AUTOMAKE $INCLUDEDEPS || fail "automake"
+echo ">>> 00boot: running autoconf"
+$AUTOCONF || fail "autoconf"
+
+echo ">>> 00boot: done"
+echo "
+*****************************************************************
+*                                                               *
+*       00boot has been run.                                    *
+*                                                               *
+*       Now run './configure' with appropriate options          *
+*       to configure LALApps.                                   *
+*                                                               *
+*       See the LALApps README file for futher instructions     *
+*                                                               *
+*****************************************************************"
+
