set the grid proxy correctly and limit the number of pre scripts that run to three Original: ef65817583cf675b942a2734c80b1bf490d516e8

diff --git a/lalapps/src/inspiral/ihope.in b/lalapps/src/inspiral/ihope.in
--- a/lalapps/src/inspiral/ihope.in
+++ b/lalapps/src/inspiral/ihope.in
@@ -1080,15 +1080,100 @@ if [ -f ${TMP_EXEC_DIR}/${UEBER_CONCRETE_DAG}.lock ] ; then
   exit 1
 fi
 
-ID=`id -u`
+# The theory here is to find the longest living
+# proxy certificate and copy it into the default
+# location so that workflows can find it even after
+# the user has logged out. This is necessary because
+# Condor and condor_dagman do not yet properly cache
+# and manage credentials to make them available to all
+# jobs in the workflow, and other tools make assumptions
+# about where a proxy, service, or user certificate is located 
+# on the file system and do not properly find valid 
+# existing credentials using the proper GSI search algorithm.
+#
+# This is not a great solution because there can be quite
+# valid reasons to have multiple credentials with different
+# lifetimes, and it presents a security risk to circumvent
+# the state and move files around without knowing why the
+# state is the way it is.
+#
+# But to support LIGO users we are doing it at this time
+# until better tooling is available.
+#
+# Assumes grid-proxy-info is in PATH
 
-if [ -n "$X509_USER_PROXY" ] && [ ! -e /tmp/x509up_u"$ID" ] ; then
-   cp $X509_USER_PROXY /tmp/x509up_u${ID}
+if ! `/usr/bin/which grid-proxy-info > /dev/null 2>&1` ; then
+    echo "ERROR: cannot find grid-proxy-info in PATH";
+    exit 1
 fi
 
-export X509_USER_PROXY=/tmp/x509up_u${ID}
+# default location for proxy certificates based on uid
+x509_default="/tmp/x509up_u`id -u`"
+
+# if X509_USER_PROXY is defined and has a lifetime of > 1 hour
+# compare to any existing default and copy it into place if 
+# and only if its lifetime is greater than the default
+if [ -n "$X509_USER_PROXY" ] ; then
+    echo "X509_USER_PROXY=${X509_USER_PROXY}"
+    if `grid-proxy-info -file ${X509_USER_PROXY} -exists -valid 1:0` ; then
+        nsec=`grid-proxy-info -file ${X509_USER_PROXY} -timeleft`
+        echo "Lifetime of ${X509_USER_PROXY} ${nsec} seconds"
+        if [ -e ${x509_default} ] ; then
+            echo "Proxy exists at default location"
+            if `grid-proxy-info -file ${x509_default} -exists -valid 1:0` ; then
+                nsec=`grid-proxy-info -file ${X509_USER_PROXY} -timeleft`
+                echo "Lifetime of default ${nsec} seconds"
+                env_life=`grid-proxy-info -file ${X509_USER_PROXY} -timeleft`
+                def_life=`grid-proxy-info -file ${x509_default} -timeleft`
+                if [ ${env_life} -gt ${def_life} ] ; then
+                    cp ${X509_USER_PROXY} ${x509_default}
+                    echo "Lifetime of ${X509_USER_PROXY} > default"
+                    echo "Copied ${X509_USER_PROXY} into default location"
+                else
+                    echo "Lifetime of default > ${X509_USER_PROXY}"
+                    echo "Leaving default in place"
+                fi
+            else
+                echo "Lifetime of default < 1 hour"
+                cp ${X509_USER_PROXY} ${x509_default}
+                echo "Lifetime of ${X509_USER_PROXY} > default"
+                echo "Copied ${X509_USER_PROXY} into default location"
+            fi
+        else
+            echo "No proxy at default location"
+            cp ${X509_USER_PROXY} $x509_default
+            echo "Copied ${X509_USER_PROXY} into default location"
+        fi
+    else
+        echo "Lifetime of ${X509_USER_PROXY} < 1 hour"
+        echo "Ignoring ${X509_USER_PROXY}"
+        echo "Assuming default location for proxy"
+    fi
+else
+    echo "X509_USER_PROXY not set"
+    echo "Assuming default location for proxy"
+fi
+
+# when we get here we can assume that if a valid proxy with lifetime > 1 exists
+# then it is in the default location, so test for it now
+valid=`grid-proxy-info -file ${x509_default} -exists -valid 1:0 > /dev/null 2>&1`
+if ! ${valid} ; then
+    echo "ERROR: could not find proxy with lifetime > 1 hour"
+    exit 1
+fi
+
+# if we get here valid proxy with lifetime > 1 hour was 
+# found so print out details for the record
+grid-proxy-info -file ${x509_default} -all
+
+# set X509_USER_PROXY to the default now
+X509_USER_PROXY=${x509_default}
+export X509_USER_PROXY
+
+# set specific condor variables needed by pegasus
 export _CONDOR_DAGMAN_LOG_ON_NFS_IS_ERROR=FALSE
 export _CONDOR_DAGMAN_COPY_TO_SPOOL=False
+export _CONDOR_DAGMAN_MAX_PRE=3
 
 if [ -f ${TMP_EXEC_DIR}/${UEBER_CONCRETE_DAG} ] ; then
   pegasus-run --conf ${IHOPE_RUN_DIR}/pegasus.properties --nodatabase ${TMP_EXEC_DIR}/.
