ci: fix bug in retry function

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -481,7 +481,8 @@ docker:tags:stretch:
           echo "Command failed. Attempt $n/$max:"
           sleep $delay;
         else
-          fail "The command has failed after $n attempts."
+          echo "The command has failed after $n attempts." 1>&2
+          exit 1
         fi
       }
     done
