SWIG wrappings Mk. II: build system - native automake builds, instead of through mkoct.m/setup.py scripts - wrapping interface generated by Python script, using XML output from   SWIG run on a preprocessing interface to get header information - file renames: swiglal*=common, lal*swig=lal*-specific - myriad other changes Original: 2fae8bee4dd0876ce7c3de6c97120ac0738c8c75

diff --git a/lal/swig/Makefile.am b/lal/swig/Makefile.am
--- a/lal/swig/Makefile.am
+++ b/lal/swig/Makefile.am
@@ -1,1 +1,103 @@
-SUBDIRS = octave python
+# Top-level SWIG build makefile.
+# Author: Karl Wette, 2011, 2012
+
+# make subdirectories
+SUBDIRS = . octave python
+
+if SWIG_BUILD
+
+# SWIG interface file
+swig_iface = @PACKAGE_NAME@swig.i
+
+# SWIG interface header list
+swig_iface_headers = $(top_builddir)/swig/@PACKAGE_NAME@swig_headers.list
+
+# SWIG preprocessing interface
+swig_iface_preproc = @PACKAGE_NAME@swig_preproc.i
+swig_iface_preproc_xml = @PACKAGE_NAME@swig_preproc.xml
+
+# SWIG preprocessing interface dependencies file
+swig_iface_preproc_deps = ./$(DEPDIR)/@PACKAGE_NAME@swig_preproc.deps
+$(swig_iface_preproc_deps) : $(swig_iface_headers) Makefile
+	@echo '#dummy' > $@
+@am__include@ @am__quote@./$(DEPDIR)/@PACKAGE_NAME@swig_preproc.deps@am__quote@
+
+# SWIG preprocessing interface flags
+swig_preprocflags = -xml -xmllite -includeall -ignoremissing -w201
+
+# script which builds SWIG interface header
+swig_generate_iface = $(srcdir)/generate_swiglal_iface.py
+
+# SWIG interface tests header
+swig_iface_test = @PACKAGE_NAME@swig_test.i
+
+# include headers in SWIG interface header list
+swig_extra_headers = $(swig_iface_test)
+
+# installation location for SWIG interfaces
+swigincludedir = $(includedir)/lal
+
+# SWIG interfaces to install
+EXTRA_HEADERS =
+nodist_swiginclude_HEADERS = $(swig_iface)
+swiginclude_HEADERS = $(SWIG_IFACES) $(swig_iface_test)
+
+# extra distribution files
+EXTRA_DIST = $(swig_generate_iface)
+
+# clean files
+CLEANFILES = \
+	$(swig_iface_preproc) \
+	$(swig_iface_preproc_xml) \
+	$(swig_iface)
+DISTCLEANFILES = \
+	$(swig_iface_preproc_deps) \
+	$(swig_iface_headers)
+
+# delete failed targets
+rm_targets = { rm -f $@; exit 1; }
+
+# create links to SWIG interfaces
+.PHONY : swig_iface_links
+swig_iface_links :
+	@for file in $(nodist_swiginclude_HEADERS) $(swiginclude_HEADERS); do \
+		srcdir=$(abs_srcdir); \
+		builddir=$(abs_builddir); \
+		incldir=$(abs_top_builddir)/include/lal; \
+		if test ! -r $${incldir}/$${file}; then \
+			rm -f $${incldir}/$${file}; \
+			if test -f $${srcdir}/$${file}; then \
+				$(LN_S) $${srcdir}/$${file} $${incldir}; \
+			elif test -f $${builddir}/$${file}; then \
+				$(LN_S) $${builddir}/$${file} $${incldir}; \
+			fi; \
+		fi; \
+	done
+
+# build SWIG preprocessing interface file
+$(swig_iface_preproc) : $(swig_iface_headers) Makefile
+	@$(MAKE) swig_iface_links
+	$(AM_V_GEN)echo '// $@: generated by Makefile' > $@; \
+	echo "%module $(SWIG_IFACE_NAME)_preproc;" >> $@; \
+	echo "#define SWIGLAL(...)" >> $@; \
+	headers=`cat $(swig_iface_headers) | $(SED) 's|^.*:||'`; \
+	for header in $$headers $(swig_extra_headers); do \
+		echo "%include <lal/$${header}>" >> $@; \
+	done
+
+# generate SWIG parse tree of preprocessing interface file
+$(swig_iface_preproc_xml) : $(swig_iface_preproc)
+	$(AM_V_GEN)$(SWIG) $(SWIG_SWIGFLAGS) $(swig_preprocflags) -MD -MF $(swig_iface_preproc_deps) -o $@ $< || $(rm_targets)
+
+# generate SWIG interface file
+export PACKAGE_NAME
+export SWIG_MODULE_DEPENDS
+export SWIG_SYMBOL_PREFIXES
+export swig_iface_preproc
+export swig_iface_preproc_xml
+export swig_iface
+$(swig_iface) : $(swig_iface_preproc_xml) $(swig_generate_iface)
+	$(AM_V_GEN)$(PYTHON) $(swig_generate_iface) || $(rm_targets)
+	@$(MAKE) swig_iface_links
+
+endif
