Doxygen: raise explicit error in case of missing tag files - refs #5604 Original: 5c4a8e9e7f1d03a64af266054731ee55df050ed5

diff --git a/lal/doxygen/Makefile.am b/lal/doxygen/Makefile.am
--- a/lal/doxygen/Makefile.am
+++ b/lal/doxygen/Makefile.am
@@ -33,6 +33,14 @@ html-local: Makefile $(CONFIG_CLEAN_FILES)
 			doxygen_version="$${doxygen_version}-$${gitid}$${unclean}"; \
 		fi; \
 	fi; \
+	for tagfile in $(DOXYGEN_TAGFILES); do \
+		tagfile=`echo "$${tagfile}" | $(SED) 's/=.*$$//'`; \
+		if ! test -r "$${tagfile}"; then \
+			echo "$(subdir)/Makefile: ERROR: missing tag file $${tagfile}" >&2; \
+			echo "$(subdir)/Makefile: (hint: you may need to rebuild the Doxygen documentation for the corresponding library)" >&2; \
+			exit 1; \
+		fi; \
+	done; \
 	export doxygen_tagfiles; doxygen_tagfiles="$(DOXYGEN_TAGFILES)"; \
 	export doxygen_quiet; doxygen_quiet="$(doxygen_quiet)"; \
 	export doxygen_exclude; doxygen_exclude=`cat $(abs_srcdir)/exclude.list | tr '\n' ' '`; \
