Move lalapps/src/pulsar/ applications to lalpulsar/bin/
- lalapps/src/pulsar/Makefile.am: clean up old build products from subdirectories

diff --git a/lalpulsar/bin/Makefile.am b/lalpulsar/bin/Makefile.am
--- a/lalpulsar/bin/Makefile.am
+++ b/lalpulsar/bin/Makefile.am
@@ -5,6 +5,63 @@ TESTS =
 include $(top_srcdir)/gnuscripts/lalsuite_help2man.am
 include $(top_srcdir)/gnuscripts/lalsuite_python.am
 
+# -- Subdirectories -------------
+
+SUBDIRS = \
+	Tools \
+	SFTTools \
+	FITSTools \
+	MakeData \
+	Fscan \
+	CreateEphemeris \
+	Fstatistic \
+	HeterodyneSearch \
+	Hough \
+	HoughFstat \
+	GCT \
+	CrossCorr \
+	SidebandSearch \
+	TwoSpect \
+	Weave \
+	$(END_OF_LINE)
+
+# Because many tests in lalpulsar/bin/ call executables from other
+# subdirectories in lalpulsar/bin/, it is safest to make sure the whole of
+# lalpulsar/bin/ is built first
+check-recursive: all-recursive
+
+# All C executables under lalpulsar/bin/ must be executed by at least one test
+# script run by "make check". The following rules enforce this requirement.
+.PHONY: clean-execs-tested-logs check-execs-are-tested
+
+check-recursive: clean-execs-tested-logs
+check-local: check-execs-are-tested
+
+clean-execs-tested-logs:
+	@tested_logfiles=`find $(builddir) -name '.tested_*.log'`; \
+	for file in $${tested_logfiles}; do \
+		echo '# empty' > "$${file}"; \
+	done
+
+check-execs-are-tested:
+	@tested_logfiles=`find $(builddir) -name '.tested_*.log'`; \
+	not_tested=`$(AWK) ' \
+	BEGIN { anyprog = 0 } \
+	$$1 == "programs" { anyprog = 1; for (i = 3; i <= NF; ++i) { prog[$$i] = 1; progpath[$$i] = $$2 "/" $$i } } \
+	$$1 == "tested" { for (i = 2; i <= NF; ++i) { tested[$$i] = 1; } } \
+	END { if (anyprog) { for (e in prog) { if (!tested[e]) { print progpath[e]; } } } else { print "NONE"; } } \
+	' $${tested_logfiles} /dev/null | $(SED) 's|^$(subdir)/||' | sort`; \
+	if test "X$${not_tested}" = XNONE; then \
+		exit 0; \
+	fi; \
+	if test "X$${not_tested}" != X; then \
+		printf "\nERROR: the following C executables under lalpulsar/bin/ have not been tested:\n" >&2; \
+		printf "   %s\n" $${not_tested} >&2; \
+		printf "\n" >&2; \
+		exit 1; \
+	fi; \
+	printf "OK: all C executables under lalpulsar/bin/ have been tested\n"
+
 # -- C programs -------------
 
 bin_PROGRAMS = \
