pre-commit: add hook to check that .gitignore are sorted, entries in right place
- Replaces part of lint:gitignore check
- Run lint:gitignore only for merge pipelines

diff --git a/.gitlab/ci/lint.yml b/.gitlab/ci/lint.yml
--- a/.gitlab/ci/lint.yml
+++ b/.gitlab/ci/lint.yml
@@ -250,49 +250,39 @@ lint:gitignore:
     - .build-job
     - .lint
   image: igwn/lalsuite-dev:el8
-  needs: []
   script:
-    # check that .gitignore entries are in the right place
-    - |
-      status=0
-      for file in .gitignore lal*/.gitignore; do
-        basedir=`dirname ${file}`
-        for line in `cat ${file}`; do
-          subdir=`echo ${line} | sed 's|^/||;s|/.*||'`
-          if test -f "${basedir}/${subdir}/.gitignore"; then
-            echo "ERROR: line '${line}' in '${file}' should be in '${basedir}/${subdir}/.gitignore'"
-            status=1
-          fi
-        done
-      done
-      test ${status} -eq 0 || exit ${status}
     # build in source directory, including tests
     - ./00boot
     - ./configure ${ENABLE_NIGHTLY} --enable-doxygen --enable-python --enable-swig-python
     - make -j${CPU_COUNT} VERBOSE=1 all
     - make -j${CPU_COUNT} VERBOSE=1 check TESTS=
+    # install pre-commit
+    - |
+      python3.11 -m venv .venv
+      source .venv/bin/activate
+      python3 -m pip install --upgrade pip
+      python3 -m pip install pre-commit
     # check for build files not in .gitignore
     - |
       status=0
-      for line in `git status --short | sed -n 's|^?? ||p'`; do
-        subdir=`echo ${line} | sed 's|/.*||'`
-        rempath=`echo ${line} | sed "s|^${subdir}/||"`
-        if test -f "${subdir}/.gitignore"; then
-          echo "ERROR: please add '${rempath}' to '${subdir}/.gitignore'"
-        else
-          echo "ERROR: please add '${line}' to '.gitignore'"
-        fi
+      git status --short | sed -n 's|^?? ||p' >> .gitignore
+      pre-commit run -a fix-gitignore-entries
+      if ! git diff --quiet; then
+        echo "------------------------------------------------------------------------"
+        echo "The following entries are missing from the .gitignore files:"
+        echo "------------------------------------------------------------------------"
+        git diff
+        echo "------------------------------------------------------------------------"
         status=1
-      done
-      test ${status} -eq 0 || exit ${status}
+      fi
+      ./common/code-quality-scripts/git_diff_to_code_quality_report "missing .gitignore entries" > code-quality-gitignore.json
+      exit ${status}
   artifacts:
-    # upload some files to debug failures
-    paths:
-      - config.log
-      - Makefile
-      - lal*/config.log
-      - lal*/Makefile
-    when: on_failure
+    reports:
+      codequality: code-quality-gitignore.json
+  rules:
+    - !reference [.ci-lint, rules]
+    - !reference [.ci-merge-build, rules]
 
 lint:pretty:
   extends:
@@ -312,6 +302,3 @@ lint:pretty:
   artifacts:
     reports:
       codequality: code-quality-pretty.json
-  rules:
-    - !reference [.ci-lint, rules]
-    - !reference [.ci-merge-build, rules]
